apiVersion: v1
kind: ServiceAccount
metadata:
  name: waypoint-runner
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: default
  name: waypoint-runner-role
rules:
  - apiGroups: ['']
    resources: ['namespaces']
    verbs: ['create', 'get', 'watch', 'list']
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: waypoint-runner-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: waypoint-runner
    namespace: default
roleRef:
  kind: ClusterRole
  name: waypoint-runner-role
  apiGroup: ''
